name: RadioBrowserKit CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test RadioBrowserKit
      run: xcodebuild -scheme RadioBrowserKit -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" -resultBundlePath TestResults.xcresult test

    - name: XCResultTool
      uses: kishikawakatsumi/xcresulttool@v1.0.3
      with:
          path: TestResults.xcresult
      if: success() || failure()



# - name: Compile...
#       run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme RadioBrowserKit -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
#     - name: Run Tests...
#       run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme RadioBrowserKit -resultBundlePath TestResults.xcresult -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
